version: 2.1

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest

    docker:
      - image: circleci/python:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}-{{ checksum "requirements.dev.txt" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-

      - run:
          name: Install Python Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            make dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}-{{ checksum "requirements.dev.txt" }}

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            make test

      # TODO: Store test artifacts

workflows:
  version: 2
  build:
    jobs:
      - test:
          version: "2.7"
      - test:
          version: "3.4"
      - test:
          version: "3.5"
      - test:
          version: "3.6"
      - test:
          version: "3.7"
