version: 2.1

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout

  lint:
    parameters:
      version:
        type: string
        default: latest

    docker:
      - image: circleci/python:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-

      # TODO: Install dependecies

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
