version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

  lint:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test:
        requires:
          - lint
