version: 2.1

commands:
  initialize:
    parameters:
      version:
        type: string
        default: latest
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-<< parameters.version >>-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}-{{ checksum "requirements.dev.txt" }}
            - v1-dependencies-<< parameters.version >>-{{ .Branch }}-
            - v1-dependencies-<< parameters.version >>-

      - run:
          name: Install Python Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            make dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}-{{ checksum "requirements.dev.txt" }}

  make:
    parameters:
      target:
        type: string
    steps:
      - run:
          name: "make << parameters.target >>"
          command: |
            . venv/bin/activate
            make << parameters.target >>

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest

    docker:
      - image: circleci/python:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - initialize:
          version: << parameters.version >>

      - make:
          target: lint

      - make:
          target: test

      # TODO: Store test artifacts

  deploy:
    parameters:
      version:
        type: string
        default: latest

    docker:
      - image: circleci/python:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - initialize
      - make:
          target: deploy
      - store_artifacts:
          path: dist/

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: "python3.4-test"
          version: "3.4"
      - test:
          name: "python3.5-test"
          version: "3.5"
      - test:
          name: "python3.6-test"
          version: "3.6"
      - test:
          name: "python3.7-test"
          version: "3.7"
      - deploy:
          requires:
            - python3.4-test
            - python3.5-test
            - python3.6-test
            - python3.7-test
          filters:
            branches:
              only: master
